
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class DictionaryRecord
{
    private readonly System.Collections.Generic.Dictionary<int, demo.Dictionary> _dataMap;
    private readonly System.Collections.Generic.List<demo.Dictionary> _dataList;
    
    public DictionaryRecord(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.Dictionary>();
        _dataList = new System.Collections.Generic.List<demo.Dictionary>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.Dictionary _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = demo.Dictionary.DeserializeDictionary(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.Dictionary> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.Dictionary> DataList => _dataList;

    public demo.Dictionary GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public demo.Dictionary Get(int key) => _dataMap[key];
    public demo.Dictionary this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

