
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class ExdataRecord
{
    private readonly System.Collections.Generic.Dictionary<int, demo.Exdata> _dataMap;
    private readonly System.Collections.Generic.List<demo.Exdata> _dataList;
    
    public ExdataRecord(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.Exdata>();
        _dataList = new System.Collections.Generic.List<demo.Exdata>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.Exdata _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = demo.Exdata.DeserializeExdata(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.Exdata> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.Exdata> DataList => _dataList;

    public demo.Exdata GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public demo.Exdata Get(int key) => _dataMap[key];
    public demo.Exdata this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

