
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class GlobalSettingRecord
{
    private readonly System.Collections.Generic.Dictionary<int, demo.GlobalSetting> _dataMap;
    private readonly System.Collections.Generic.List<demo.GlobalSetting> _dataList;
    
    public GlobalSettingRecord(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.GlobalSetting>();
        _dataList = new System.Collections.Generic.List<demo.GlobalSetting>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.GlobalSetting _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = demo.GlobalSetting.DeserializeGlobalSetting(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.GlobalSetting> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.GlobalSetting> DataList => _dataList;

    public demo.GlobalSetting GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public demo.GlobalSetting Get(int key) => _dataMap[key];
    public demo.GlobalSetting this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

