
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public partial class IconRecord
{
    private readonly System.Collections.Generic.Dictionary<int, demo.Icon> _dataMap;
    private readonly System.Collections.Generic.List<demo.Icon> _dataList;
    
    public IconRecord(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.Icon>();
        _dataList = new System.Collections.Generic.List<demo.Icon>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo.Icon _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = demo.Icon.DeserializeIcon(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.Icon> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.Icon> DataList => _dataList;

    public demo.Icon GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public demo.Icon Get(int key) => _dataMap[key];
    public demo.Icon this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

