
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public sealed partial class Icon : Luban.BeanBase
{
    public Icon(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["atlas"].IsString) { throw new SerializationException(); }  Atlas = _buf["atlas"]; }
        { if(!_buf["sprite"].IsString) { throw new SerializationException(); }  Sprite = _buf["sprite"]; }
    }

    public static Icon DeserializeIcon(JSONNode _buf)
    {
        return new demo.Icon(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 图集
    /// </summary>
    public readonly string Atlas;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Sprite;
   
    public const int __ID__ = 749609412;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "atlas:" + Atlas + ","
        + "sprite:" + Sprite + ","
        + "}";
    }
}

}

