
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public demo.GlobalSettingRecord GlobalSettingRecord {get; }
    public demo.ExdataRecord ExdataRecord {get; }
    public demo.IconRecord IconRecord {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        GlobalSettingRecord = new demo.GlobalSettingRecord(loader("demo_globalsettingrecord"));
        ExdataRecord = new demo.ExdataRecord(loader("demo_exdatarecord"));
        IconRecord = new demo.IconRecord(loader("demo_iconrecord"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        GlobalSettingRecord.ResolveRef(this);
        ExdataRecord.ResolveRef(this);
        IconRecord.ResolveRef(this);
    }
}

}
