
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public Common.GlobalSetting GlobalSetting {get; }
    public Common.Flag Flag {get; }
    public Common.ExtendData ExtendData {get; }
    public Common.Condition Condition {get; }
    public Common.Dictionary Dictionary {get; }
    public Res.Item Item {get; }
    public Res.Icon Icon {get; }
    public UI.HomeTab HomeTab {get; }
    public Merge.MergeItem MergeItem {get; }
    public Merge.MergeFormula MergeFormula {get; }
    public Shop.Store Store {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        GlobalSetting = new Common.GlobalSetting(loader("common_globalsetting"));
        Flag = new Common.Flag(loader("common_flag"));
        ExtendData = new Common.ExtendData(loader("common_extenddata"));
        Condition = new Common.Condition(loader("common_condition"));
        Dictionary = new Common.Dictionary(loader("common_dictionary"));
        Item = new Res.Item(loader("res_item"));
        Icon = new Res.Icon(loader("res_icon"));
        HomeTab = new UI.HomeTab(loader("ui_hometab"));
        MergeItem = new Merge.MergeItem(loader("merge_mergeitem"));
        MergeFormula = new Merge.MergeFormula(loader("merge_mergeformula"));
        Store = new Shop.Store(loader("shop_store"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        GlobalSetting.ResolveRef(this);
        Flag.ResolveRef(this);
        ExtendData.ResolveRef(this);
        Condition.ResolveRef(this);
        Dictionary.ResolveRef(this);
        Item.ResolveRef(this);
        Icon.ResolveRef(this);
        HomeTab.ResolveRef(this);
        MergeItem.ResolveRef(this);
        MergeFormula.ResolveRef(this);
        Store.ResolveRef(this);
    }
}

}
