
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Shop
{
public sealed partial class StoreRecord : Luban.BeanBase
{
    public StoreRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadInt();
        Name_Ref = null;
        Icon = _buf.ReadInt();
        Icon_Ref = null;
        Desc = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Res = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Res.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Count = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Count.Add(_e0);}}
        Quality = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Price = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Price.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Exdata = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Exdata.Add(_e0);}}
    }

    public static StoreRecord DeserializeStoreRecord(ByteBuf _buf)
    {
        return new Shop.StoreRecord(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 物品名
    /// </summary>
    public readonly int Name;
    public Common.DictionaryRecord Name_Ref;
    /// <summary>
    /// 图标表ID
    /// </summary>
    public readonly int Icon;
    public Res.IconRecord Icon_Ref;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly int Desc;
    /// <summary>
    /// 物品
    /// </summary>
    public readonly System.Collections.Generic.List<int> Res;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly System.Collections.Generic.List<int> Count;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly System.Collections.Generic.List<int> Price;
    public readonly System.Collections.Generic.List<int> Exdata;
   
    public const int __ID__ = 1102520730;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Name_Ref = tables.Dictionary.GetOrDefault(Name);
        Icon_Ref = tables.Icon.GetOrDefault(Icon);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "desc:" + Desc + ","
        + "res:" + Luban.StringUtil.CollectionToString(Res) + ","
        + "count:" + Luban.StringUtil.CollectionToString(Count) + ","
        + "quality:" + Quality + ","
        + "price:" + Luban.StringUtil.CollectionToString(Price) + ","
        + "exdata:" + Luban.StringUtil.CollectionToString(Exdata) + ","
        + "}";
    }
}

}

