
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Shop
{
public partial class Store
{
    private readonly System.Collections.Generic.Dictionary<int, Shop.StoreRecord> _dataMap;
    private readonly System.Collections.Generic.List<Shop.StoreRecord> _dataList;
    
    public Store(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Shop.StoreRecord>();
        _dataList = new System.Collections.Generic.List<Shop.StoreRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Shop.StoreRecord _v;
            _v = Shop.StoreRecord.DeserializeStoreRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Shop.StoreRecord> DataMap => _dataMap;
    public System.Collections.Generic.List<Shop.StoreRecord> DataList => _dataList;

    public Shop.StoreRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Shop.StoreRecord Get(int key) => _dataMap[key];
    public Shop.StoreRecord this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

