
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Res
{
public partial class Icon
{
    private readonly System.Collections.Generic.Dictionary<int, Res.IconRecord> _dataMap;
    private readonly System.Collections.Generic.List<Res.IconRecord> _dataList;
    
    public Icon(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Res.IconRecord>();
        _dataList = new System.Collections.Generic.List<Res.IconRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Res.IconRecord _v;
            _v = Res.IconRecord.DeserializeIconRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Res.IconRecord> DataMap => _dataMap;
    public System.Collections.Generic.List<Res.IconRecord> DataList => _dataList;

    public Res.IconRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Res.IconRecord Get(int key) => _dataMap[key];
    public Res.IconRecord this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

