
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Res
{
public partial class IconRecord
{
    private readonly System.Collections.Generic.Dictionary<int, Res.Icon> _dataMap;
    private readonly System.Collections.Generic.List<Res.Icon> _dataList;
    
    public IconRecord(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Res.Icon>();
        _dataList = new System.Collections.Generic.List<Res.Icon>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Res.Icon _v;
            _v = Res.Icon.DeserializeIcon(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Res.Icon> DataMap => _dataMap;
    public System.Collections.Generic.List<Res.Icon> DataList => _dataList;

    public Res.Icon GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Res.Icon Get(int key) => _dataMap[key];
    public Res.Icon this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

