
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Res
{
public partial class Item
{
    private readonly System.Collections.Generic.Dictionary<int, Res.ItemRecord> _dataMap;
    private readonly System.Collections.Generic.List<Res.ItemRecord> _dataList;
    
    public Item(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Res.ItemRecord>();
        _dataList = new System.Collections.Generic.List<Res.ItemRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Res.ItemRecord _v;
            _v = Res.ItemRecord.DeserializeItemRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Res.ItemRecord> DataMap => _dataMap;
    public System.Collections.Generic.List<Res.ItemRecord> DataList => _dataList;

    public Res.ItemRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Res.ItemRecord Get(int key) => _dataMap[key];
    public Res.ItemRecord this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

