
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Res
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadInt();
        Name_Ref = null;
        Icon = _buf.ReadInt();
        Icon_Ref = null;
        Type = _buf.ReadInt();
    }

    public static Item DeserializeItem(ByteBuf _buf)
    {
        return new Res.Item(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    public readonly int Name;
    public Common.Text Name_Ref;
    /// <summary>
    /// 图标表ID
    /// </summary>
    public readonly int Icon;
    public Res.Icon Icon_Ref;
    /// <summary>
    /// 物品类型
    /// </summary>
    public readonly int Type;
   
    public const int __ID__ = -337758239;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Name_Ref = tables.TextRecord.GetOrDefault(Name);
        Icon_Ref = tables.IconRecord.GetOrDefault(Icon);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "type:" + Type + ","
        + "}";
    }
}

}

