
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Merge
{
public partial class MergeFormula
{
    private readonly System.Collections.Generic.Dictionary<int, Merge.MergeFormulaRecord> _dataMap;
    private readonly System.Collections.Generic.List<Merge.MergeFormulaRecord> _dataList;
    
    public MergeFormula(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Merge.MergeFormulaRecord>();
        _dataList = new System.Collections.Generic.List<Merge.MergeFormulaRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Merge.MergeFormulaRecord _v;
            _v = Merge.MergeFormulaRecord.DeserializeMergeFormulaRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Merge.MergeFormulaRecord> DataMap => _dataMap;
    public System.Collections.Generic.List<Merge.MergeFormulaRecord> DataList => _dataList;

    public Merge.MergeFormulaRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Merge.MergeFormulaRecord Get(int key) => _dataMap[key];
    public Merge.MergeFormulaRecord this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

