
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Merge
{
public sealed partial class MergeFormulaRecord : Luban.BeanBase
{
    public MergeFormulaRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        Quality = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Main = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Main.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Secondary = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Secondary.Add(_e0);}}
        Exdata = _buf.ReadInt();
    }

    public static MergeFormulaRecord DeserializeMergeFormulaRecord(ByteBuf _buf)
    {
        return new Merge.MergeFormulaRecord(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 物品类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 主要
    /// </summary>
    public readonly System.Collections.Generic.List<int> Main;
    /// <summary>
    /// 次要
    /// </summary>
    public readonly System.Collections.Generic.List<int> Secondary;
    public readonly int Exdata;
   
    public const int __ID__ = 509599157;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "quality:" + Quality + ","
        + "main:" + Luban.StringUtil.CollectionToString(Main) + ","
        + "secondary:" + Luban.StringUtil.CollectionToString(Secondary) + ","
        + "exdata:" + Exdata + ","
        + "}";
    }
}

}

