
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Merge
{
public sealed partial class MergeItemRecord : Luban.BeanBase
{
    public MergeItemRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadInt();
        Name_Ref = null;
        Icon = _buf.ReadInt();
        Icon_Ref = null;
        Desc = _buf.ReadInt();
        Type = _buf.ReadInt();
        MaxCount = _buf.ReadInt();
        Quality = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);From = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); From.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Exdata = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Exdata.Add(_e0);}}
    }

    public static MergeItemRecord DeserializeMergeItemRecord(ByteBuf _buf)
    {
        return new Merge.MergeItemRecord(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 物品名
    /// </summary>
    public readonly int Name;
    public Common.DictionaryRecord Name_Ref;
    /// <summary>
    /// 图标表ID
    /// </summary>
    public readonly int Icon;
    public Res.IconRecord Icon_Ref;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly int Desc;
    /// <summary>
    /// 物品类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 最大数量
    /// </summary>
    public readonly int MaxCount;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 获取途径
    /// </summary>
    public readonly System.Collections.Generic.List<int> From;
    public readonly System.Collections.Generic.List<int> Exdata;
   
    public const int __ID__ = 1353756070;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Name_Ref = tables.Dictionary.GetOrDefault(Name);
        Icon_Ref = tables.Icon.GetOrDefault(Icon);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "desc:" + Desc + ","
        + "type:" + Type + ","
        + "maxCount:" + MaxCount + ","
        + "quality:" + Quality + ","
        + "from:" + Luban.StringUtil.CollectionToString(From) + ","
        + "exdata:" + Luban.StringUtil.CollectionToString(Exdata) + ","
        + "}";
    }
}

}

