
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Merge
{
public partial class MergeItem
{
    private readonly System.Collections.Generic.Dictionary<int, Merge.MergeItemRecord> _dataMap;
    private readonly System.Collections.Generic.List<Merge.MergeItemRecord> _dataList;
    
    public MergeItem(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Merge.MergeItemRecord>();
        _dataList = new System.Collections.Generic.List<Merge.MergeItemRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Merge.MergeItemRecord _v;
            _v = Merge.MergeItemRecord.DeserializeMergeItemRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Merge.MergeItemRecord> DataMap => _dataMap;
    public System.Collections.Generic.List<Merge.MergeItemRecord> DataList => _dataList;

    public Merge.MergeItemRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Merge.MergeItemRecord Get(int key) => _dataMap[key];
    public Merge.MergeItemRecord this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

