
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Merge
{
public sealed partial class MergeFormulaRecord : Luban.BeanBase
{
    public MergeFormulaRecord(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = _buf["quality"]; }
        { var __json0 = _buf["main"]; if(!__json0.IsArray) { throw new SerializationException(); } Main = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Main.Add(__v0); }   }
        { var __json0 = _buf["secondary"]; if(!__json0.IsArray) { throw new SerializationException(); } Secondary = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Secondary.Add(__v0); }   }
        { if(!_buf["exdata"].IsNumber) { throw new SerializationException(); }  Exdata = _buf["exdata"]; }
    }

    public static MergeFormulaRecord DeserializeMergeFormulaRecord(JSONNode _buf)
    {
        return new Merge.MergeFormulaRecord(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 物品类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 主要
    /// </summary>
    public readonly System.Collections.Generic.List<int> Main;
    /// <summary>
    /// 次要
    /// </summary>
    public readonly System.Collections.Generic.List<int> Secondary;
    public readonly int Exdata;
   
    public const int __ID__ = 509599157;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "quality:" + Quality + ","
        + "main:" + Luban.StringUtil.CollectionToString(Main) + ","
        + "secondary:" + Luban.StringUtil.CollectionToString(Secondary) + ","
        + "exdata:" + Exdata + ","
        + "}";
    }
}

}

