
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Res
{
public partial class Item
{
    private readonly System.Collections.Generic.Dictionary<int, Res.ItemRecord> _dataMap;
    private readonly System.Collections.Generic.List<Res.ItemRecord> _dataList;
    
    public Item(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Res.ItemRecord>();
        _dataList = new System.Collections.Generic.List<Res.ItemRecord>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Res.ItemRecord _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Res.ItemRecord.DeserializeItemRecord(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Res.ItemRecord> DataMap => _dataMap;
    public System.Collections.Generic.List<Res.ItemRecord> DataList => _dataList;

    public Res.ItemRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Res.ItemRecord Get(int key) => _dataMap[key];
    public Res.ItemRecord this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

