
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Res
{
public partial class ItemRecord
{
    private readonly System.Collections.Generic.Dictionary<int, Res.Item> _dataMap;
    private readonly System.Collections.Generic.List<Res.Item> _dataList;
    
    public ItemRecord(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Res.Item>();
        _dataList = new System.Collections.Generic.List<Res.Item>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Res.Item _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Res.Item.DeserializeItem(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Res.Item> DataMap => _dataMap;
    public System.Collections.Generic.List<Res.Item> DataList => _dataList;

    public Res.Item GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Res.Item Get(int key) => _dataMap[key];
    public Res.Item this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

