
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.demo
{
public sealed partial class Dictionary : Luban.BeanBase
{
    public Dictionary(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Cn = _buf.ReadString();
        En = _buf.ReadString();
        Cn1 = _buf.ReadString();
    }

    public static Dictionary DeserializeDictionary(ByteBuf _buf)
    {
        return new demo.Dictionary(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 中文
    /// </summary>
    public readonly string Cn;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string En;
    /// <summary>
    /// 繁中
    /// </summary>
    public readonly string Cn1;
   
    public const int __ID__ = 1821766049;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Cn:" + Cn + ","
        + "En:" + En + ","
        + "Cn1:" + Cn1 + ","
        + "}";
    }
}

}

