
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.demo
{
public sealed partial class Exdata : Luban.BeanBase
{
    public Exdata(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Value = _buf.ReadString();
    }

    public static Exdata DeserializeExdata(ByteBuf _buf)
    {
        return new demo.Exdata(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 数据
    /// </summary>
    public readonly string Value;
   
    public const int __ID__ = -1275319960;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "value:" + Value + ","
        + "}";
    }
}

}

