
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.demo
{
public partial class HomeTabRecord
{
    private readonly System.Collections.Generic.Dictionary<int, demo.HomeTab> _dataMap;
    private readonly System.Collections.Generic.List<demo.HomeTab> _dataList;
    
    public HomeTabRecord(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.HomeTab>();
        _dataList = new System.Collections.Generic.List<demo.HomeTab>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            demo.HomeTab _v;
            _v = demo.HomeTab.DeserializeHomeTab(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo.HomeTab> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.HomeTab> DataList => _dataList;

    public demo.HomeTab GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public demo.HomeTab Get(int key) => _dataMap[key];
    public demo.HomeTab this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

