
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Shop
{
public sealed partial class StoreRecord : Luban.BeanBase
{
    public StoreRecord(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsNumber) { throw new SerializationException(); }  Name = _buf["name"]; }
        Name_Ref = null;
        { if(!_buf["icon"].IsNumber) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        Icon_Ref = null;
        { if(!_buf["desc"].IsNumber) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { var __json0 = _buf["res"]; if(!__json0.IsArray) { throw new SerializationException(); } Res = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Res.Add(__v0); }   }
        { var __json0 = _buf["count"]; if(!__json0.IsArray) { throw new SerializationException(); } Count = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Count.Add(__v0); }   }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = _buf["quality"]; }
        { var __json0 = _buf["price"]; if(!__json0.IsArray) { throw new SerializationException(); } Price = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Price.Add(__v0); }   }
        { var __json0 = _buf["exdata"]; if(!__json0.IsArray) { throw new SerializationException(); } Exdata = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Exdata.Add(__v0); }   }
    }

    public static StoreRecord DeserializeStoreRecord(JSONNode _buf)
    {
        return new Shop.StoreRecord(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 物品名
    /// </summary>
    public readonly int Name;
    public Common.DictionaryRecord Name_Ref;
    /// <summary>
    /// 图标表ID
    /// </summary>
    public readonly int Icon;
    public Res.IconRecord Icon_Ref;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly int Desc;
    /// <summary>
    /// 物品
    /// </summary>
    public readonly System.Collections.Generic.List<int> Res;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly System.Collections.Generic.List<int> Count;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly System.Collections.Generic.List<int> Price;
    public readonly System.Collections.Generic.List<int> Exdata;
   
    public const int __ID__ = 1102520730;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Name_Ref = tables.Dictionary.GetOrDefault(Name);
        Icon_Ref = tables.Icon.GetOrDefault(Icon);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "desc:" + Desc + ","
        + "res:" + Luban.StringUtil.CollectionToString(Res) + ","
        + "count:" + Luban.StringUtil.CollectionToString(Count) + ","
        + "quality:" + Quality + ","
        + "price:" + Luban.StringUtil.CollectionToString(Price) + ","
        + "exdata:" + Luban.StringUtil.CollectionToString(Exdata) + ","
        + "}";
    }
}

}

