
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Common
{
public sealed partial class ExDataRecord : Luban.BeanBase
{
    public ExDataRecord(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        InitValue = _buf.ReadInt();
        MaxValue = _buf.ReadInt();
        RefreshRule = _buf.ReadInt();
        RefreshTime = _buf.ReadInt();
        CanClientChange = _buf.ReadInt();
        Condition = _buf.ReadInt();
    }

    public static ExDataRecord DeserializeExDataRecord(ByteBuf _buf)
    {
        return new Common.ExDataRecord(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 初始值
    /// </summary>
    public readonly int InitValue;
    /// <summary>
    /// 最大值
    /// </summary>
    public readonly int MaxValue;
    /// <summary>
    /// 刷新规则
    /// </summary>
    public readonly int RefreshRule;
    /// <summary>
    /// 刷新时间
    /// </summary>
    public readonly int RefreshTime;
    /// <summary>
    /// client可修改
    /// </summary>
    public readonly int CanClientChange;
    /// <summary>
    /// 计入条件
    /// </summary>
    public readonly int Condition;
   
    public const int __ID__ = -273147695;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "initValue:" + InitValue + ","
        + "maxValue:" + MaxValue + ","
        + "refreshRule:" + RefreshRule + ","
        + "refreshTime:" + RefreshTime + ","
        + "canClientChange:" + CanClientChange + ","
        + "condition:" + Condition + ","
        + "}";
    }
}

}

