
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Common
{
public partial class ExtendData
{
    private readonly System.Collections.Generic.Dictionary<int, Common.ExDataRecord> _dataMap;
    private readonly System.Collections.Generic.List<Common.ExDataRecord> _dataList;
    
    public ExtendData(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Common.ExDataRecord>();
        _dataList = new System.Collections.Generic.List<Common.ExDataRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Common.ExDataRecord _v;
            _v = Common.ExDataRecord.DeserializeExDataRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Common.ExDataRecord> DataMap => _dataMap;
    public System.Collections.Generic.List<Common.ExDataRecord> DataList => _dataList;

    public Common.ExDataRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Common.ExDataRecord Get(int key) => _dataMap[key];
    public Common.ExDataRecord this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

