
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Common
{
public sealed partial class GlobalSetting : Luban.BeanBase
{
    public GlobalSetting(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Value = _buf.ReadInt();
    }

    public static GlobalSetting DeserializeGlobalSetting(ByteBuf _buf)
    {
        return new Common.GlobalSetting(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 数据
    /// </summary>
    public readonly int Value;
   
    public const int __ID__ = 706831978;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "value:" + Value + ","
        + "}";
    }
}

}

