
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Common
{
public partial class GlobalSettingRecord
{
    private readonly System.Collections.Generic.Dictionary<int, Common.GlobalSetting> _dataMap;
    private readonly System.Collections.Generic.List<Common.GlobalSetting> _dataList;
    
    public GlobalSettingRecord(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Common.GlobalSetting>();
        _dataList = new System.Collections.Generic.List<Common.GlobalSetting>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Common.GlobalSetting _v;
            _v = Common.GlobalSetting.DeserializeGlobalSetting(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Common.GlobalSetting> DataMap => _dataMap;
    public System.Collections.Generic.List<Common.GlobalSetting> DataList => _dataList;

    public Common.GlobalSetting GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Common.GlobalSetting Get(int key) => _dataMap[key];
    public Common.GlobalSetting this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

