
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public Common.GlobalSettingRecord GlobalSettingRecord {get; }
    public Common.ExdataRecord ExdataRecord {get; }
    public Common.TextRecord TextRecord {get; }
    public Res.ItemRecord ItemRecord {get; }
    public Res.IconRecord IconRecord {get; }
    public UI.HomeTabRecord HomeTabRecord {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        GlobalSettingRecord = new Common.GlobalSettingRecord(loader("common_globalsettingrecord"));
        ExdataRecord = new Common.ExdataRecord(loader("common_exdatarecord"));
        TextRecord = new Common.TextRecord(loader("common_textrecord"));
        ItemRecord = new Res.ItemRecord(loader("res_itemrecord"));
        IconRecord = new Res.IconRecord(loader("res_iconrecord"));
        HomeTabRecord = new UI.HomeTabRecord(loader("ui_hometabrecord"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        GlobalSettingRecord.ResolveRef(this);
        ExdataRecord.ResolveRef(this);
        TextRecord.ResolveRef(this);
        ItemRecord.ResolveRef(this);
        IconRecord.ResolveRef(this);
        HomeTabRecord.ResolveRef(this);
    }
}

}
