
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public demo.GlobalSettingRecord GlobalSettingRecord {get; }
    public demo.ExdataRecord ExdataRecord {get; }
    public demo.IconRecord IconRecord {get; }
    public demo.HomeTabRecord HomeTabRecord {get; }
    public demo.DictionaryRecord DictionaryRecord {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        GlobalSettingRecord = new demo.GlobalSettingRecord(loader("demo_globalsettingrecord"));
        ExdataRecord = new demo.ExdataRecord(loader("demo_exdatarecord"));
        IconRecord = new demo.IconRecord(loader("demo_iconrecord"));
        HomeTabRecord = new demo.HomeTabRecord(loader("demo_hometabrecord"));
        DictionaryRecord = new demo.DictionaryRecord(loader("demo_dictionaryrecord"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        GlobalSettingRecord.ResolveRef(this);
        ExdataRecord.ResolveRef(this);
        IconRecord.ResolveRef(this);
        HomeTabRecord.ResolveRef(this);
        DictionaryRecord.ResolveRef(this);
    }
}

}
