
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Common
{
public sealed partial class ConditionRecord : Luban.BeanBase
{
    public ConditionRecord(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["Flags"].IsNumber) { throw new SerializationException(); }  Flags = _buf["Flags"]; }
    }

    public static ConditionRecord DeserializeConditionRecord(JSONNode _buf)
    {
        return new Common.ConditionRecord(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// flag1
    /// </summary>
    public readonly int Flags;
   
    public const int __ID__ = 618953545;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Flags:" + Flags + ","
        + "}";
    }
}

}

