
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Common
{
public partial class Dictionary
{
    private readonly System.Collections.Generic.Dictionary<int, Common.DictionaryRecord> _dataMap;
    private readonly System.Collections.Generic.List<Common.DictionaryRecord> _dataList;
    
    public Dictionary(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Common.DictionaryRecord>();
        _dataList = new System.Collections.Generic.List<Common.DictionaryRecord>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Common.DictionaryRecord _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Common.DictionaryRecord.DeserializeDictionaryRecord(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Common.DictionaryRecord> DataMap => _dataMap;
    public System.Collections.Generic.List<Common.DictionaryRecord> DataList => _dataList;

    public Common.DictionaryRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Common.DictionaryRecord Get(int key) => _dataMap[key];
    public Common.DictionaryRecord this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

