
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Common
{
public sealed partial class FlagRecord : Luban.BeanBase
{
    public FlagRecord(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsNumber) { throw new SerializationException(); }  Name = _buf["name"]; }
        Name_Ref = null;
        { if(!_buf["icon"].IsNumber) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        Icon_Ref = null;
        { if(!_buf["desc"].IsNumber) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["maxCount"].IsNumber) { throw new SerializationException(); }  MaxCount = _buf["maxCount"]; }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = _buf["quality"]; }
        { var __json0 = _buf["from"]; if(!__json0.IsArray) { throw new SerializationException(); } From = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  From.Add(__v0); }   }
        { var __json0 = _buf["exdata"]; if(!__json0.IsArray) { throw new SerializationException(); } Exdata = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Exdata.Add(__v0); }   }
    }

    public static FlagRecord DeserializeFlagRecord(JSONNode _buf)
    {
        return new Common.FlagRecord(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 物品名
    /// </summary>
    public readonly int Name;
    public Common.DictionaryRecord Name_Ref;
    /// <summary>
    /// 图标表ID
    /// </summary>
    public readonly int Icon;
    public Res.IconRecord Icon_Ref;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly int Desc;
    /// <summary>
    /// 物品类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 最大数量
    /// </summary>
    public readonly int MaxCount;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 获取途径
    /// </summary>
    public readonly System.Collections.Generic.List<int> From;
    public readonly System.Collections.Generic.List<int> Exdata;
   
    public const int __ID__ = 1650415296;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Name_Ref = tables.Dictionary.GetOrDefault(Name);
        Icon_Ref = tables.Icon.GetOrDefault(Icon);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "desc:" + Desc + ","
        + "type:" + Type + ","
        + "maxCount:" + MaxCount + ","
        + "quality:" + Quality + ","
        + "from:" + Luban.StringUtil.CollectionToString(From) + ","
        + "exdata:" + Luban.StringUtil.CollectionToString(Exdata) + ","
        + "}";
    }
}

}

