
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Common
{
public partial class GlobalSetting
{
    private readonly System.Collections.Generic.Dictionary<int, Common.GlobalSettingRecord> _dataMap;
    private readonly System.Collections.Generic.List<Common.GlobalSettingRecord> _dataList;
    
    public GlobalSetting(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Common.GlobalSettingRecord>();
        _dataList = new System.Collections.Generic.List<Common.GlobalSettingRecord>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Common.GlobalSettingRecord _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Common.GlobalSettingRecord.DeserializeGlobalSettingRecord(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Common.GlobalSettingRecord> DataMap => _dataMap;
    public System.Collections.Generic.List<Common.GlobalSettingRecord> DataList => _dataList;

    public Common.GlobalSettingRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Common.GlobalSettingRecord Get(int key) => _dataMap[key];
    public Common.GlobalSettingRecord this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

