
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Common
{
public partial class TextRecord
{
    private readonly System.Collections.Generic.Dictionary<int, Common.Text> _dataMap;
    private readonly System.Collections.Generic.List<Common.Text> _dataList;
    
    public TextRecord(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Common.Text>();
        _dataList = new System.Collections.Generic.List<Common.Text>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Common.Text _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Common.Text.DeserializeText(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Common.Text> DataMap => _dataMap;
    public System.Collections.Generic.List<Common.Text> DataList => _dataList;

    public Common.Text GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Common.Text Get(int key) => _dataMap[key];
    public Common.Text this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

