
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Common
{
public sealed partial class Text : Luban.BeanBase
{
    public Text(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["Cn"].IsString) { throw new SerializationException(); }  Cn = _buf["Cn"]; }
        { if(!_buf["En"].IsString) { throw new SerializationException(); }  En = _buf["En"]; }
        { if(!_buf["Cn1"].IsString) { throw new SerializationException(); }  Cn1 = _buf["Cn1"]; }
    }

    public static Text DeserializeText(JSONNode _buf)
    {
        return new Common.Text(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 中文
    /// </summary>
    public readonly string Cn;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string En;
    /// <summary>
    /// 繁中
    /// </summary>
    public readonly string Cn1;
   
    public const int __ID__ = -303109296;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Cn:" + Cn + ","
        + "En:" + En + ","
        + "Cn1:" + Cn1 + ","
        + "}";
    }
}

}

