
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.UI
{
public partial class HomeTab
{
    private readonly System.Collections.Generic.Dictionary<int, UI.HomeTabRecord> _dataMap;
    private readonly System.Collections.Generic.List<UI.HomeTabRecord> _dataList;
    
    public HomeTab(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, UI.HomeTabRecord>();
        _dataList = new System.Collections.Generic.List<UI.HomeTabRecord>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            UI.HomeTabRecord _v;
            _v = UI.HomeTabRecord.DeserializeHomeTabRecord(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, UI.HomeTabRecord> DataMap => _dataMap;
    public System.Collections.Generic.List<UI.HomeTabRecord> DataList => _dataList;

    public UI.HomeTabRecord GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UI.HomeTabRecord Get(int key) => _dataMap[key];
    public UI.HomeTabRecord this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

