
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.UI
{
public sealed partial class HomeTab : Luban.BeanBase
{
    public HomeTab(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);IconIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); IconIds.Add(_e0);}}
        Name = _buf.ReadInt();
        Name_Ref = null;
    }

    public static HomeTab DeserializeHomeTab(ByteBuf _buf)
    {
        return new UI.HomeTab(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 图集
    /// </summary>
    public readonly System.Collections.Generic.List<int> IconIds;
    public System.Collections.Generic.List<Res.Icon> IconIds_Ref;
    /// <summary>
    /// 字典
    /// </summary>
    public readonly int Name;
    public Common.Text Name_Ref;
   
    public const int __ID__ = -1296691012;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        IconIds_Ref = new System.Collections.Generic.List<Res.Icon>();
        foreach (var _v in IconIds) { IconIds_Ref.Add(tables.IconRecord.GetOrDefault(_v)); }

        Name_Ref = tables.TextRecord.GetOrDefault(Name);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "iconIds:" + Luban.StringUtil.CollectionToString(IconIds) + ","
        + "name:" + Name + ","
        + "}";
    }
}

}

