
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.demp
{
public sealed partial class HomeTab : Luban.BeanBase
{
    public HomeTab(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Atlas = _buf.ReadString();
        Sprite = _buf.ReadString();
    }

    public static HomeTab DeserializeHomeTab(ByteBuf _buf)
    {
        return new demp.HomeTab(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 图集
    /// </summary>
    public readonly string Atlas;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Sprite;
   
    public const int __ID__ = -274418676;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "atlas:" + Atlas + ","
        + "sprite:" + Sprite + ","
        + "}";
    }
}

}

