
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.UI
{
public sealed partial class HomeTabRecord : Luban.BeanBase
{
    public HomeTabRecord(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["iconIds"]; if(!__json0.IsArray) { throw new SerializationException(); } IconIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  IconIds.Add(__v0); }   }
        { if(!_buf["name"].IsNumber) { throw new SerializationException(); }  Name = _buf["name"]; }
        Name_Ref = null;
    }

    public static HomeTabRecord DeserializeHomeTabRecord(JSONNode _buf)
    {
        return new UI.HomeTabRecord(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 图集
    /// </summary>
    public readonly System.Collections.Generic.List<int> IconIds;
    public System.Collections.Generic.List<Res.IconRecord> IconIds_Ref;
    /// <summary>
    /// 字典
    /// </summary>
    public readonly int Name;
    public Common.DictionaryRecord Name_Ref;
   
    public const int __ID__ = 547941421;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        IconIds_Ref = new System.Collections.Generic.List<Res.IconRecord>();
        foreach (var _v in IconIds) { IconIds_Ref.Add(tables.Icon.GetOrDefault(_v)); }

        Name_Ref = tables.Dictionary.GetOrDefault(Name);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "iconIds:" + Luban.StringUtil.CollectionToString(IconIds) + ","
        + "name:" + Name + ","
        + "}";
    }
}

}

